### ISSUE TITLE
ファイルアップロード処理をドラッグアンドドロップ式にする

### ISSUE THREAD

**Issue by qh73xe** [qh73xe/mri-vuewer.dev#21]
## TODO
- [x] HOME 画面に mp4 ファイルを drag and drop したタイミングでデータ読み込み処理を実行
- [x] HOME 画面に フォルダ を drag and drop したタイミングで フォルダ内のmp4 ファイルをすべて読み込む処理を作成
- [x] データ読み込み処理基底クラスを作成
- [x] ドラック and ドロップのファイル処理基底クラスを作成

## 参考
- ファイルのドロップ処理: https://reffect.co.jp/vue/drag-drop-file-upload
- ディレクトリのドロップ処理; https://qiita.com/wannabe/items/2b2f59a626313a8f58d4

**Comment by qh73xe** [comment]
とりあえずmp4 のドラックアンドドロップ処理を作成
